# action.yaml
name: "JFrog CLI"
author: "Deep Anandrao"
branding:
    icon: "command"
    color: "orange"
description: "Connects to JFrog Artifactory and executes JFrog CLI commands"
runs:
    using: "docker"
    image: "Dockerfile"
