# action.yaml
name: "JFrog CLI"
description: "Connects to JFrog Artifactory and executes JFrog CLI commands"
author: "Deep Anandrao"
branding:
    icon: "command"
    color: "orange"
runs:
    using: "docker"
    image: "Dockerfile"
    args: 
        - 'jfrog rt ping'
